### ISSUE TITLE
UnicodeEncodeError occurrs when dealing with an ods spreadsheet with Chinese content

### ISSUE THREAD

**Issue by brlin-tw** [winged/ods2sql#1]
```
$ ods2sql.py <test.ods | sqlite3 test.sqlite.db
Traceback (most recent call last):
  File "ods2sql.py", line 288, in <module>
    render(parse(), rowtitles)
  File "ods2sql.py", line 217, in parse
    parser.Parse(xmlstring, True)
  File "ods2sql.py", line 199, in end_element
    self.path[-1].cleanup()
  File "ods2sql.py", line 55, in cleanup
    if isinstance(self[-1], Element) and not self[-1].isempty(): break
  File "ods2sql.py", line 137, in isempty
    return self.content() == ''
  File "ods2sql.py", line 147, in content
    return "".join([repr(x) for x in self.children()])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by winged** [comment]
Hi, Awesome, I'm glad this is useful for somebody else :)
Sorry for the delay, I was on vacation. Can you upload an example file where it fails?
